# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
 
name: PR Runner
 
on:
  push:
    branches:
      - '**'
      - '!main'
 
permissions: read-all
 
jobs:
  Version_Checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
 
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        cache: 'pip'
 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./.github/workflows/requirements.txt

    - name: Get Pull Request Number
      id: pr
      run: echo "pull_request_number=$(gh pr view --json number -q .number || echo "")" >> $GITHUB_OUTPUT
      env:
        GITHUB_TOKEN: ${{ secrets.READ_TOKEN }}

    - name: Check PR
      id: cpr
      run: python check_db_scripts.py ${{ steps.pr.outputs.pull_request_number }}
      env:
        READ_TOKEN: ${{ secrets.READ_TOKEN }}


#Uncomment and add this here
# name: Get PR Number on PUSH event

# on: [push]

# jobs:
#   push:
#     runs-on: ubuntu-latest
#     if: ${{ github.event_name == 'push' }}
#     steps:
#       - uses: actions/checkout@v2.3.4
#         with:
#           fetch-depth: 0
#       - name: Get Pull Request Number
#         id: pr
#         run: echo "pull_request_number=$(gh pr view --json number -q .number || echo "")" >> $GITHUB_OUTPUT
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       - run: echo ${{ steps.pr.outputs.pull_request_number }}


